apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
spec:
 replicas: 1
 selector:
   matchLabels:
     app:  jenkins-server
     tier: backend
 template:
   metadata:
     labels:
       app:  jenkins-server
       tier: backend
   spec:

      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: pvc-efs
      containers:
      - name: jenkins
        image: 019273956931.dkr.ecr.eu-west-1.amazonaws.com/shani-ecr-repo:jenkins-server
        command: [ "/bin/sh" ]
        args: [ "-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 2; done" ]
        volumeMounts:
        - name: jenkins-data
          mountPath: /data
