apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
spec:
 replicas: 1
 selector:
   matchLabels:
     app:  jenkins-server
     tier: backend
 template:
   metadata:
     labels:
       app:  jenkins-server
       tier: backend
   spec:
      securityContext:
       fsGroup: 1000
       runAsUser: 1000
      volumes:
      - name: jenkins-server-data
        persistentVolumeClaim:
          claimName: shanid-pvc
      containers:
      - name: jenkins
        image: 019273956931.dkr.ecr.eu-west-1.amazonaws.com/shani-ecr-repo:jenkins-server
        ports:
          - name: httpport
            containerPort: 8080
          - name: jnlpport
            containerPort: 50000
        initContainers:
          - name: fix-permissions
            image: busybox
            command: [ "sh", "-c", "chown -R 1000:1000 /var/jenkins_home" ]
            securityContext:
              privileged: true
        volumeMounts:
        - name: jenkins-server-data
          mountPath: /var/jenkins_home
