apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
spec:
 replicas: 1
 selector:
   matchLabels:
     app:  jenkins-server
     tier: backend
 template:
   metadata:
     labels:
       app:  jenkins-server
       tier: backend
   spec:
      volumes:
      - name: jenkins-server-data
        persistentVolumeClaim:
          claimName: shani-pvc-efs
      containers:
      - name: jenkins
        image: 019273956931.dkr.ecr.eu-west-1.amazonaws.com/shani-ecr-repo:jenkins-server
        volumeMounts:
        - name: jenkins-server-data
          mountPath: /var/jenkins_home
