apiVersion: v1
kind: Service
metadata:
  name: jenkins-server
  labels:
    app: jenkins-server
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: jenkins-server
