apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-server-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/jenkins"