
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv
#spec:
#  capacity:
#    storage: 5Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: efs-sc
#  csi:
#    driver: efs.csi.aws.com
#

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0afcb65d9ccb39a2d