apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: shani-jenkins
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: jenkins-server
  type: LoadBalancer
  ports:
    - port: 8080
      name: httpport
      targetPort: 8080
    - port: 50000
      targetPort: 50000
      name: jnlpport

