apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/component: backend


    spec:
      imagePullSecrets:
      - name: secretdockerhub

      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: nginx-pvc
      containers:
      - name: nginx
        image: shaniben/shani-repo:nginx
        volumeMounts:
        - mountPath: "/var/www/html"
          name: pv-storage

        resources:
          requests:
            cpu: "0.5"
            memory: "55Mi"
          limits:
            cpu: "1"
            memory: "90Mi"

        livenessProbe:
          exec:
            command:
            - cat
            - /var/www/html/index.html
          initialDelaySeconds: 5
          periodSeconds: 7



