apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
  labels:
    app: polybot
spec:
  selector:
    matchLabels:
      app: polybot
  replicas: 1
  template:
    metadata:
      labels:
        app: polybot
    spec:

      volumes:
      - name: polybot-pv-storage
        persistentVolumeClaim:
          claimName: polybot-pvc
      containers:
      - name: polybot
        image: shaniben/shani-repo:poly-bot-106
        volumeMounts:
        - mountPath: "/polybot/pvc"
          name: polybot-pv-storage
        #imagePullSecrets:
        #  - name: secretdockerhub


        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: polybotsecret
              key: token


        resources:
          requests:
            cpu: "0.5"
            memory: "55Mi"
          limits:
            cpu: "1"
            memory: "90Mi"
