apiVersion: v1
kind: PersistentVolume
metadata:
  name: polybot-pv
  labels:
    type: local
spec:
  storageClassName: manualsc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"